"""Tests for the per-output provenance manifests (constitution Principle III).

Two things matter: the manifest records enough to tie an output to the exact
bytes and parameters that produced it, and writing it never disturbs the output
itself.
"""

import hashlib
import os

import pandas as pd
import pytest
import yaml

from whaletracks.cli import _common
from whaletracks.cli.plot_ranges import estimate_ranges
from whaletracks.common import provenance

PKG_ROOT = os.path.dirname(os.path.dirname(__file__))
CONFIG = os.path.join(PKG_ROOT, "whaletracks", "config", "ranges_fin.yaml")
COMMITTED = os.path.join(
    PKG_ROOT, "data", "fin_whale", "Marianas_auto_B20_CORTADO_TEST_v2.csv"
)


def test_file_digest_matches_hashlib(tmp_path):
    p = tmp_path / "x.bin"
    p.write_bytes(b"multipath")
    assert provenance.file_digest(p) == "sha256:" + hashlib.sha256(b"multipath").hexdigest()


def test_manifest_records_output_config_and_inputs(tmp_path):
    src = tmp_path / "in.csv"
    src.write_text("a,b\n1,2\n3,4\n")
    out = tmp_path / "out.csv"
    out.write_text("r\n1\n2\n3\n")
    cfg = tmp_path / "cfg.yaml"
    cfg.write_text("threshold: 7\n")

    path = provenance.write_manifest(
        out, command="whaletracks-test", config_path=str(cfg),
        parameters={"threshold": 7},
        source={"network": "XF", "station": "B20", "channel": None},
        inputs=[str(src)],
    )
    assert path == str(out) + provenance.MANIFEST_SUFFIX
    doc = yaml.safe_load(open(path))

    assert doc["file"]["name"] == "out.csv"
    assert doc["file"]["rows"] == 3            # header excluded
    assert doc["file"]["sha256"] == provenance.file_digest(out)
    assert doc["generated"]["command"] == "whaletracks-test"
    assert doc["generated"]["utc"].endswith("Z")
    assert doc["config"]["sha256"] == provenance.file_digest(cfg)
    assert doc["config"]["parameters"] == {"threshold": 7}
    assert doc["inputs"][0]["sha256"] == provenance.file_digest(src)
    assert doc["inputs"][0]["rows"] == 2
    # Unknown source fields are omitted rather than written as nulls.
    assert doc["source"] == {"network": "XF", "station": "B20"}


def test_manifest_detects_a_changed_input(tmp_path):
    src = tmp_path / "in.csv"
    src.write_text("a\n1\n")
    out = tmp_path / "out.csv"
    out.write_text("r\n1\n")
    before = yaml.safe_load(open(
        provenance.write_manifest(out, command="c", inputs=[str(src)])
    ))

    src.write_text("a\n2\n")       # input edited after the fact
    assert provenance.file_digest(src) != before["inputs"][0]["sha256"]


def test_shipped_file_manifest_claims_no_run(tmp_path):
    """A file the repo ships but did not generate must not claim a code version."""
    f = tmp_path / "provided.csv"
    f.write_text("a\n1\n")
    doc = yaml.safe_load(open(provenance.write_manifest(
        f, command=None, notes="Provided with the demonstration."
    )))
    assert "command" not in doc["generated"]
    assert "whaletracks_version" not in doc["generated"]
    assert "git_commit" not in doc["generated"]
    assert "not generated by a whaletracks run" in doc["generated"]["by"]
    assert doc["notes"].startswith("Provided")


def test_time_span_from_series():
    s = pd.Series(["2012-03-04T00:00:00", "2012-10-20T12:00:00", None])
    span = provenance.time_span(s)
    assert span["start"].startswith("2012-03-04")
    assert span["end"].startswith("2012-10-20")
    assert provenance.time_span(pd.Series([], dtype="object")) is None


@pytest.mark.skipif(not os.path.isfile(COMMITTED), reason="committed B20 output not present")
def test_ranging_writes_manifest_without_changing_the_csv(tmp_path):
    """The real pipeline: B20 ranging still reproduces the committed bytes."""
    cfg = _common.load_yaml(CONFIG)
    for key in ("bellhop_dir", "calls_dir"):
        cfg[key] = os.path.join(PKG_ROOT, cfg[key])
    cfg["output_dir"] = str(tmp_path)

    estimate_ranges(cfg, "B20", save=None, show=False, config_path=CONFIG)

    out = tmp_path / os.path.basename(COMMITTED)
    assert provenance.file_digest(out) == provenance.file_digest(COMMITTED)

    doc = yaml.safe_load(open(str(out) + provenance.MANIFEST_SUFFIX))
    assert doc["source"]["station"] == "B20"
    assert doc["source"]["network"] == "XF"
    assert doc["config"]["parameters"]["ranging"]["min_center"] == 2
    assert doc["config"]["parameters"]["ranging"]["min_window"] == 10
    assert doc["config"]["parameters"]["valid_end"] == "2013-02-01"
    # Every input is named and hashed: detections, autocorrelation, BELLHOP.
    assert len(doc["inputs"]) == 3
    assert any("bellhop" in i["file"] for i in doc["inputs"])
    assert all(i["sha256"].startswith("sha256:") for i in doc["inputs"])
